#---
sdkversion: 5.2.0
name: RhoMobileApp1
version: '1.2'
vendor: rhomobile
build: debug
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphoneos8.3
  provisionprofile: "WildCard Development COM"
  production:
    mobileprovision_file: "./production/wildcard_com.mobileprovision"
    certificate_file: "./production/Certificates_Raghu_new.p12"
    certificate_password: "Zebra@123"
  codesignidentity: "iPhone Developer: Raghavendra Kamble (W8L77BLH6N)"
  BundleIdentifier: com.rhomobileapp1
  BundleURLScheme: rhomobileapp1
wp8:
  productid: ca054410-a528-0132-3596-00000b3d6e45
android:
  manifest_template: AndroidManifest.erb
  version: 2.3.3
  logcatFilter: APP:I StrictMode:I DEBUG:I *:E
wm: ''
win32:
  deployqt: '1'
  deploymsvc: '1'
extensions:
- rhoconnect-client
app_type: rhoelements
capabilities: []
